/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_named_data_jni_psync_PSync */

#ifndef _Included_net_named_data_jni_psync_PSync
#define _Included_net_named_data_jni_psync_PSync
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_named_data_jni_psync_PSync
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_named_1data_jni_psync_PSync_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_named_data_jni_psync_PSync
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_named_1data_jni_psync_PSync_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
